services:
  - type: web
    name: alpha-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /up
    autoDeployTrigger: commit
    envVars:
      - key: APP_NAME
        value: Alpha
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DB_URL
        sync: false
      - key: DB_MIGRATION_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

  - type: web
    name: alpha-web
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: API_INTERNAL_URL
        sync: false
